name: RaccoonMischief
main: me.evanskistudios.rm.RaccoonMischief
version: 2.0
api-version: 1.19
authors: [EvanskiStudios]
description: Raccoons
commands:
  RMVER:
    description: Returns the version of RaccoonMischief
    usage: /RMVER
  RMtestDeath:
    description: Lowers player health to make it easier to test deaths
    usage: /RMtestDeath
  RMGetCfg:
    description: Returns value of Config key
    usage: /RMGetCfg <Key>
  RMReloadCFG:
    description: Reloads the Config.yml file
    usage: /RMReloadCFG
