name: RaccoonMischief
version: '${project.version}'
main: me.evanskistudios.rm.RaccoonMischief
api-version: 1.19
authors: [ EvanskiStudios ]
description: Raccoons
commands:
  RMVER:
    description: Returns the version of RaccoonMischief
    usage: /RMVER
  RMtestDeath:
    description: Lowers player health to make it easier to test deaths
    usage: /RMtestDeath
  RMGetCfg:
    description: Returns value of Config key
    usage: /RMGetCfg <Key>
  RMReloadCFG:
    description: Reloads the Config.yml file
    usage: /RMReloadCFG
  RMGive:
    description: Gives custom RM items
    usage: "/RMGive <item> <(Optional) Int: Amount>"
  RMShowCraft:
    description: Shows the recipe of an RM Item
    usage: "/RMShowCraft <RM Recipe>"
  RMEnchant:
    description: Enchants held item with RM Enchant
    usage: "/RMEnchant <RM Enchant> <(Optional) Int: Level>"
  RMQuickTest:
    description: Quick RM Test
    usage: "/RMQuickTest"